name: Release
on:
  push:
    tags:
      - "v*.*.*"
env:
  CARGO_INCREMENTAL: 0
permissions:
  contents: write

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      cargo_version: ${{ steps.cargo_version.outputs.value }}
      cargo_cache_key: ${{ steps.cargo_cache_key.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set cargo cache key
        id: cargo_cache_key
        run: |
          CARGO_CACHE_KEY="${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
          echo "value=$CARGO_CACHE_KEY" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ steps.cargo_cache_key.outputs.value }}
          id: cache-cargo-release

      - name: Get Cargo version
        id: cargo_version
        run: |
          VERSION=$(cargo read-manifest --manifest-path ./tinted-builder-rust/Cargo.toml | jq -r ".version")
          echo "value=$VERSION" >> $GITHUB_OUTPUT

      - name: Abort if there is a Cargo.toml and git tag mismatch
        run: |
          if [[ "v${{ steps.cargo_version.outputs.value }}" != "${{ github.ref_name }}" ]]; then
            echo "There is a Cargo.toml version and git tag mismatch." && exit 1;
          fi

  test:
    needs: setup-environment
    uses: ./.github/workflows/test.yml
    with:
      cache-key: ${{ needs.setup-environment.outputs.cargo_cache_key }}

  publish-dry-run:
    needs: [setup-environment, test]
    runs-on: ubuntu-latest
    env:
      CARGO_CACHE_KEY: ${{ needs.setup-environment.outputs.cargo_cache_key }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ env.CARGO_CACHE_KEY }}
          id: cache-cargo-test

      - name: Attempt a publish dryrun
        run: |
          cargo publish --dry-run -p tinted-builder-rust

  release:
    needs: [setup-environment, publish-dry-run]
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    env:
      CARGO_CACHE_KEY: ${{ needs.setup-environment.outputs.cargo_cache_key }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - prefix: x86_64-linux
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: false
            deb: false
          - prefix: i686-linux
            target: i686-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            deb: true
          - prefix: aarch64-linux
            target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
            deb: true
          - os: macos-11
            target: x86_64-apple-darwin
            cross: true
            deb: false
          - os: macos-11
            target: aarch64-apple-darwin
            cross: true
            deb: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      # Fetch notes from CHANGELOG.md based on cargo.toml version
      - name: Extract release notes
        id: extract_notes
        run: |
          VERSION="${{ steps.cargo_version.outputs.value }}"
          CHANGELOG_TEXT=$(sed -n "/## \[$VERSION\] /,/^## /p" "CHANGELOG.md" | sed '1d;$d')
          if [[ -n "$CHANGELOG_TEXT" ]]; then
            echo "CHANGELOG_TEXT<<EOF" >> $GITHUB_ENV
            echo "$CHANGELOG_TEXT" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ env.CARGO_CACHE_KEY }}
          id: cache-cargo-release

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: -p tinted-builder-rust --release --locked --target=${{ matrix.target }} --color=always --verbose

      - name: Install cargo-deb
        if: ${{ matrix.deb == true }}
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb

      - name: Build deb
        if: ${{ matrix.deb == true }}
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: -p tinted-builder-rust --no-build --no-strip --output=. --target=${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          files="THIRD_PARTY_LICENSES.md LICENSE README.md"
          $GITHUB_WORKSPACE/scripts/package_build \
            "THIRD_PARTY_LICENSES.md LICENSE README.md" \
            "${{ matrix.target }}" \
            "$GITHUB_WORKSPACE" \
            "${{ steps.cargo_version.outputs.value }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            *.deb
            *.tar.gz
            *.sha256

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.tar.gz
            build/*.sha256
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.cargo_version.outputs.value }}
          draft: true
          body: ${{ env.CHANGELOG_TEXT }}

      - name: Cleanup
        run: rm -r build/

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Publish to crates.io
        if: github.ref == 'refs/heads/main'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish
